### ISSUE TITLE
Get All Custom Forms for Record Type is returning NullPointerException

### ISSUE THREAD

**Issue by yaseentt** [Accela-Inc/developer-forum#47]
I'm trying to use this function https://developer.accela.com/docs/api_reference/v4.get.settings.records.types.id.customForms.html

My request:

GET /v4/settings/records/types/PubHealthSrvcs-Service.cRequest-Veterinary.cAnimal.cRegistration-VARE/customForms

The output:

{
"status": 500,
"code": "internal_server_error",
"message": "We are experiencing internal server error. Please contact Agency Administrator for assistance.",
"more": "java.lang.NullPointerException\ \ \	at com.accela.restapis.asi.util.ASIHelper.getASITableDrillByName(ASIHelper.java:874)\ \ \	at com.accela.restapis.record.RecordSettingResourceV4.builderASIMetaDefineOutput(RecordSettingResourceV4.java:349)\ \ \	at com.accela.restapis.record.RecordSettingResourceV4.getASIMetaByType(RecordSettingResourceV4.java:209)\ \ \	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\ \ \	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\ \ \	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\ \ \	at java.lang.reflect.Method.invoke(Method.java:601)\ \ \	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:166)\ \ \	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:82)\ \ \	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:122)\ \ \	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:70)\ \ \	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:57)\ \ \	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\ \ \	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)\ \ \	at java.util.concurrent.FutureTask.run(FutureTask.java:166)\ \ \	at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)\ \ \	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:95)\ \ \	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:236)\ \ \	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:89)\ \ \	at org.apache.cxf.transport.servlet.ServletDestination.invoke(ServletDestination.java:99)\ \ \	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:337)\ \ \	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:145)\ \ \	at org.apache.cxf.transport.servlet.AbstractCXFServlet.invoke(AbstractCXFServlet.java:163)\ \ \	at org.apache.cxf.transport.servlet.AbstractCXFServlet.doGet(AbstractCXFServlet.java:145)\ \ \	at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)\ \ \	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\ \ \	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\ \ \	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\ \ \	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\ \ \	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:182)\ \ \	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:84)\ \ \	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\ \ \	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)\ \ \	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:157)\ \ \	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)\ \ \	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\ \ \	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)\ \ \	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)\ \ \	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:617)\ \ \	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1754)\ \ \	at java.lang.Thread.run(Thread.java:722)\ \ ",
"traceId": "rest-1029"
}

AA version is 7.3.3.1

Thanks!

**Comment by yaseentt** [comment]
An update about this issue, the same function works fine with other record types, and if I remember correctly it used to work fine on this exact record type so I suppose a recent change broke that.

**Comment by axtheset** [comment]
@yaseentt would you be able to recreate the issue and then pull the av.biz server.log file for the same time?  This will shed some light on the issue.  We will open a ticket with the API team to review along with the biz server log.

**Comment by yaseentt** [comment]
@axtheset Hi I have copy pasted all the logged data from server.log after I generated the error

2015-01-13 16:48:56,097 INFO  [com.accela.restapis.framework.jaxrs.interceptors.JAXRSInInterceptor] rest-3855-Request path is: /v4/settings/records/types/PubHealthSrvcs-Service.cRequest-Veterinary.cAnimal.cRegistration-VARE/customForms
2015-01-13 16:48:56,097 INFO  [com.accela.restapis.framework.jaxrs.interceptors.JAXRSInInterceptor] rest-3855-Request HTTP method is: GET
2015-01-13 16:48:56,097 INFO  [com.accela.restapis.framework.jaxrs.interceptors.JAXRSInInterceptor] rest-3855-Request contentType is: */*
2015-01-13 16:48:56,097 INFO  [com.accela.restapis.framework.jaxrs.interceptors.JAXRSInInterceptor] rest-3855-Accept contentType is: application/json
2015-01-13 16:48:56,097 INFO  [com.accela.restapis.framework.jaxrs.interceptors.JAXRSInInterceptor] rest-3855-Found operation: getASIMetaByType
2015-01-13 16:48:56,112 ERROR [com.accela.restapis.framework.util.ResponseHelper] rest-3855-We are experiencing internal server error. Please contact Agency Administrator for assistance.
2015-01-13 16:48:56,112 ERROR [com.accela.restapis.framework.jaxrs.providers.RESTExceptionMapper] 
java.lang.NullPointerException
	at com.accela.restapis.asi.util.ASIHelper.getASITableDrillByName(ASIHelper.java:874)
	at com.accela.restapis.record.RecordSettingResourceV4.builderASIMetaDefineOutput(RecordSettingResourceV4.java:349)
	at com.accela.restapis.record.RecordSettingResourceV4.getASIMetaByType(RecordSettingResourceV4.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:166)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:82)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:122)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:70)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:95)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:236)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:89)
	at org.apache.cxf.transport.servlet.ServletDestination.invoke(ServletDestination.java:99)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:337)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:145)
	at org.apache.cxf.transport.servlet.AbstractCXFServlet.invoke(AbstractCXFServlet.java:163)
	at org.apache.cxf.transport.servlet.AbstractCXFServlet.doGet(AbstractCXFServlet.java:145)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:182)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:84)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:157)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:617)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1754)
	at java.lang.Thread.run(Thread.java:722)
2015-01-13 16:48:56,159 INFO  [com.accela.restapis.framework.jaxrs.providers.JSONProvider] rest-3855-Write? class com.accela.restapis.framework.model.ResponseModel, application/json

**Comment by axtheset** [comment]
@yaseentt I assume you are making this request directly through the gateway correct?

**Comment by axtheset** [comment]
I have logged this with the API team and will report back on progress.

**Comment by yaseentt** [comment]
@axtheset I'm going through the gateway yes, I can try going through the cloud if that helps detail the problem.

**Comment by axtheset** [comment]
Probably worth a try, but I'm guessing it doesn't matter.  I'll let engineering know, no update back from the team on this yet.

**Comment by axtheset** [comment]
@yaseentt can you grab a screen shot for record type 'PubHealthSrvcs-Service.cRequest-Veterinary.cAnimal.cRegistration-VARE' like this:
![screenshot-1](https://cloud.githubusercontent.com/assets/1944978/5756200/f6e9c200-9c7a-11e4-8ff7-83c47859e69a.png)

**Comment by yaseentt** [comment]
@axtheset Here is a screenshot of the requested page

![accela-asi-drilldown](https://cloud.githubusercontent.com/assets/146491/5756746/46309fe0-9ccc-11e4-9610-89726df3439f.png)
